<!-- <div class="mx-auto md:max-w-screen-md"> -->
<div class="container mx-auto max-w-xl px-2 pt-2">
  <article class="prose">
    <h1>Info</h1>
    <p>
      This markdown notebook demo created in svelte. The objective of this was
      to a create a basic static site which allows users to edit and render
      markdown.
    </p>
    <h2>Packages</h2>
    <p>
      tailwindcss. Used to create the css for all elements. The typography
      plugin was used to format the rendered markdown text. It was customized to
      use smaller margins.
    </p>
    <p>ace. Used to editor for writing markdown text.</p>
    <p>marked. Used to convert markdown strings into html.</p>
    <p>dompurify. Used to sanitize the html generated by marked.</p>
  </article>
</div>
